name = "Docsy"
license = "Apache 2.0"
licenselink = "https://gitlab.com/mdavis2810614/fhrp-pubtheme/-/blob/main/LICENSE"
description = "A Hugo theme for technical documentation sites"
homepage = "https://gitlab.com/mdavis2810614/fhrp-pubtheme"
demosite = "https://fhrp.org/"
tags = ["documentation", "multilingual", "customizable", "responsive", "docs"]
features = []
min_version = "0.110.0"

[author]
  name = "Matthew A. Davis"
  homepage = "matthewd.org"
